#!/usr/bin/env bash

BASE_ARGS=(
  -l import/init
  -e "import('Math', 'Table', 'system'); print, _print = system.print, print"
  -i
)

if (( $# > 0 )); then
    #echo "${BASE_ARGS[@]} $@";
    exec luajit "${BASE_ARGS[@]}" -- "$@"
else
    exec luajit "${BASE_ARGS[@]}"
fi

